### ISSUE TITLE
Support half days (and arbitrary hours?)

### ISSUE THREAD

**Issue by citelao** [citelao/tar2d2#6]
It would be nice to mark half days

**Comment by bkcodepoet** [comment]
Possible solution - after selecting a day, allow right-click on a day and have it pop a modal dialog box that is a simple numeric entry mechanism, with a number from 1-8 (?) indicating number of hours that day were taken off... ?

Care must be taken with new syntax not to impact existing save/load data

**Comment by citelao** [comment]
I added new functionality!

**Shift-click** will now create a half day :)

It's not a full solution, since it doesn't support mobile, but it's a good start.

**Comment by citelao** [comment]
See #15 for any lingering issues
